import { MilkmadeHat } from "./items/MilkmadeHat";
import { Loot } from "./items/Loot";
import { FoodValuesLore } from "./items/FoodValuesLore";
import { Food } from "./items/Food";
import { Crops } from "./blocks/Crops";
import { VoltGoatHandler } from "./entity/VoltGoatHandler";
new MilkmadeHat();
new Loot();
new FoodValuesLore();
new Food();
new Crops();
new VoltGoatHandler();